version: '3.8'

services:
  web:
    image: python:3.12-slim
    command:  bash -c "pip install Django && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1